AES.WebApplication/Controllers/ApplicationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AES.Entities.Shared.Net45.Models;
using AES.WebApplication.Client;

namespace AES.WebApplication.Controllers
{
    public class ApplicationController : Controller
    {
        public ApplicationSvcClient Client { get; }

        public ApplicationController()
        {
            Client = new ApplicationSvcClient();
        }

        // GET: Application
        public async Task<ActionResult> Index()
        {
            IEnumerable<Application> application = await Client.GetApplications();

            return View(application);
        }

        // GET: Application/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Application application = await Client.GetApplicationById(id);

            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // GET: Application/Create
        public async Task<ActionResult> Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Position position = null;
            using (var client = new PositionSvcClient())
            {
                position = await client.GetPositionById(id);
            }

            ViewData["PositionName"] = position.PositionName;
            ViewData["PositionId"] = position.PositionId;

            return View();
        }

        // POST: Application/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ApplicationId,Name,SSN,Address,PhoneNumber,OtherName,Email,PositionsApplied,PositionId,SalaryExpectation,FullTime,PartTime,Days,Evenings,Weekends,MondayAvailable,TuesdayAvailable,WednesdayAvailable,ThursdayAvailable,FridayAvailable,SaturdayAvailable,SundayAvailable,MostRecentEmployerName,MostRecentEmployerFromDate,MostRecentEmployerToDate,MostRecentEmployerAddress,MostRecentEmployerPhone,MostRecentEmployerSupervisor,MostRecentEmployerPosition,MostRecentEmployerStartSalary,MostRecentEmployerEndSalary,MostRecentEmployerReasonForLeaving,MostRecentEmployerResponsibilities,MiddleRecentEmployerName,MiddleRecentEmployerFromDate,MiddleRecentEmployerToDate,MiddleRecentEmployerAddress,MiddleRecentEmployerPhone,MiddleRecentEmployerSupervisor,MiddleRecentEmployerPosition,MiddleRecentEmployerStartSalary,MiddleRecentEmployerEndSalary,MiddleRecentEmployerReasonForLeaving,MiddleRecentEmployerResponsibilities,LeastRecentEmployerName,LeastRecentEmployerFromDate,LeastRecentEmployerToDate,LeastRecentEmployerAddress,LeastRecentEmployerPhone,LeastRecentEmployerSupervisor,LeastRecentEmployerPosition,LeastRecentEmployerStartSalary,LeastRecentEmployerEndSalary,LeastRecentEmployerReasonForLeaving,LeastRecentEmployerResponsibilities,MostRecentEducationName,MostRecentEducationYearsAttended,MostRecentEducationGraduated,MostRecentEducationDegreeMajor,MiddleRecentEducationName,MiddleRecentEducationYearsAttended,MiddleRecentEducationGraduated,MiddleRecentEducationDegreeMajor,LeastRecentEducationName,LeastRecentEducationYearsAttended,LeastRecentEducationGraduated,LeastRecentEducationDegreeMajor,Reference1Name,Reference1Phone,Reference1Company,Reference1Title,Reference2Name,Reference2Phone,Reference2Company,Reference2Title,Reference3Name,Reference3Phone,Reference3Company,Reference3Title,ApplicationDate")] Application application)
        {
            if (!ModelState.IsValid) return View(application);
            {
                await Client.CreateApplication(application);

                return RedirectToAction("Index");
            }
        }

        // GET: Application/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Application application = await Client.GetApplicationById(id);

            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // POST: Application/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ApplicationId,Name,SSN,Address,PhoneNumber,OtherName,Email,PositionsApplied,PositionId,SalaryExpectation,FullTime,PartTime,Days,Evenings,Weekends,MondayAvailable,TuesdayAvailable,WednesdayAvailable,ThursdayAvailable,FridayAvailable,SaturdayAvailable,SundayAvailable,MostRecentEmployerName,MostRecentEmployerFromDate,MostRecentEmployerToDate,MostRecentEmployerAddress,MostRecentEmployerPhone,MostRecentEmployerSupervisor,MostRecentEmployerPosition,MostRecentEmployerStartSalary,MostRecentEmployerEndSalary,MostRecentEmployerReasonForLeaving,MostRecentEmployerResponsibilities,MiddleRecentEmployerName,MiddleRecentEmployerFromDate,MiddleRecentEmployerToDate,MiddleRecentEmployerAddress,MiddleRecentEmployerPhone,MiddleRecentEmployerSupervisor,MiddleRecentEmployerPosition,MiddleRecentEmployerStartSalary,MiddleRecentEmployerEndSalary,MiddleRecentEmployerReasonForLeaving,MiddleRecentEmployerResponsibilities,LeastRecentEmployerName,LeastRecentEmployerFromDate,LeastRecentEmployerToDate,LeastRecentEmployerAddress,LeastRecentEmployerPhone,LeastRecentEmployerSupervisor,LeastRecentEmployerPosition,LeastRecentEmployerStartSalary,LeastRecentEmployerEndSalary,LeastRecentEmployerReasonForLeaving,LeastRecentEmployerResponsibilities,MostRecentEducationName,MostRecentEducationYearsAttended,MostRecentEducationGraduated,MostRecentEducationDegreeMajor,MiddleRecentEducationName,MiddleRecentEducationYearsAttended,MiddleRecentEducationGraduated,MiddleRecentEducationDegreeMajor,LeastRecentEducationName,LeastRecentEducationYearsAttended,LeastRecentEducationGraduated,LeastRecentEducationDegreeMajor,Reference1Name,Reference1Phone,Reference1Company,Reference1Title,Reference2Name,Reference2Phone,Reference2Company,Reference2Title,Reference3Name,Reference3Phone,Reference3Company,Reference3Title,ApplicationDate")] Application application)
        {
            if (!ModelState.IsValid) return View(application);
            {
                await Client.EditApplication(application);

                return RedirectToAction("Index");
            }
        }

        // GET: Application/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Application application = await Client.GetApplicationById(id);

            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // POST: Application/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Application application = await Client.GetApplicationById(id);
            await Client.DeleteApplication(id);
            return RedirectToAction("Index");
        }

        public ActionResult Questionnaire()
        {
            return RedirectToAction("Questionnaire/GetQuestionnaire");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                Client.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AES.WebApplication/Controllers/PositionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using AES.Entities.Shared.Net45.Models;
using AES.WebApplication.Client;

namespace AES.WebApplication.Controllers
{
    public class PositionController : Controller
    {
        private readonly PositionSvcClient _client = new PositionSvcClient();

        public PositionController()
        {
            _client = new PositionSvcClient();
        }

        // GET: Position
        public async Task<ActionResult> Index()
        {
            IEnumerable<Position> positions = await _client.GetPositions();
            return View(positions);
        }

        // GET: Position/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Position position = await _client.GetPositionById(id);

            if (position == null)
            {
                return HttpNotFound();
            }

            return View(position);
        }

        // GET: Position/Create
        public async Task<ActionResult> Create()
        {
            IEnumerable<Store> stores = null;
            using (var client = new StoreSvcClient())
            {
                stores = await client.GetStores();
            }

            var storeTitleList = new List<string>();
            var storeTitlesQuery = from s in stores select s.StoreName;

            storeTitleList.AddRange(storeTitlesQuery);
            var storeSelectList = new SelectList(storeTitleList);

            ViewBag.StoreTitles = storeSelectList;
            ViewBag.Stores = stores;

            IEnumerable<Test> tests = null;
            using (var client = new TestSvcClient())
            {
                tests = await client.GetTests();
            }

            var testQuestionList = new List<string>();
            var testTitlesQuery = from t in tests select t.TestName;

            testQuestionList.AddRange(testTitlesQuery);
            var testSelectList = new SelectList(testQuestionList);

            ViewBag.TestQuestionList = testSelectList;
            ViewBag.Tests = tests;

            return View();
        }

        // POST: Position/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [System.Web.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "PositionId,PositionName,PositionDesc,StoreId,TestId")] Position position)
        {
            if (!ModelState.IsValid) return View(position);

            await _client.CreatePosition(position);

            return RedirectToAction("Index");
        }

        // GET: Position/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Position position = await _client.GetPositionById(id);

            IEnumerable<Store> stores = null;
            using (var client = new StoreSvcClient())
            {
                stores = await client.GetStores();
            }

            var storeTitleList = new List<string>();
            var storeTitlesQuery = from s in stores select s.StoreName;

            storeTitleList.AddRange(storeTitlesQuery);
            var storeSelectList = new SelectList(storeTitleList);

            ViewBag.StoreTitles = storeSelectList;
            ViewBag.Stores = stores;

            IEnumerable<Test> tests = null;
            using (var client = new TestSvcClient())
            {
                tests = await client.GetTests();
            }

            var testQuestionList = new List<string>();
            var testTitlesQuery = from t in tests select t.TestName;

            testQuestionList.AddRange(testTitlesQuery);
            var testSelectList = new SelectList(testQuestionList);

            ViewBag.TestQuestionList = testSelectList;
            ViewBag.Tests = tests;

            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // POST: Position/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [System.Web.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PositionId,PositionName,PositionDesc,StoreId,TestId")] Position position)
        {
            if (!ModelState.IsValid) return View(position);
            await _client.EditPosition(position);

            return RedirectToAction("Index");
        }

        // GET: Position/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Position position = await _client.GetPositionById(id);

            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // POST: Position/Delete/5
        [System.Web.Mvc.HttpPost, System.Web.Mvc.ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Position position = await _client.GetPositionById(id);
            await _client.DeletePosition(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _client.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AES.WebApplication/Views/Position/Create.cshtml
@model AES.Entities.Shared.Net45.Models.Position
@{
    ViewBag.Title = "Create";
}
<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Position</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.PositionName, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.PositionName, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.PositionName, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PositionDesc, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.PositionDesc, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.PositionDesc, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StoreId, "StoreId", htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-5">
                @Html.DropDownListFor(model => model.StoreId, new SelectList(ViewBag.Stores, "StoreId", "StoreName"), new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.StoreId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestId, "Test Name", htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-5">
                @Html.DropDownListFor(model => model.TestId, new SelectList(ViewBag.Tests, "TestId", "TestName"), new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.TestId, "", new {@class = "text-danger"})
            </div>
            <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default"/>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AES.WebApplication/Views/Position/Delete.cshtml
@model AES.Entities.Shared.Net45.Models.Position

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Position</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Store.StoreLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Store.StoreLocation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Test.TestName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Test.TestName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PositionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PositionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PositionDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PositionDesc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AES.WebApplication/Views/Position/Details.cshtml
@model AES.Entities.Shared.Net45.Models.Position

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Position</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Store.StoreLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Store.StoreLocation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Test.TestName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Test.TestName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PositionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PositionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PositionDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PositionDesc)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PositionId }) |
    @Html.ActionLink("Back to List", "Index")
    <div>
        <button class="aes-btn, col-lg-offset-4">@Html.ActionLink("Apply", "Create", "Application", new {id = Model.PositionId}, null)</button>
    </div>
</p>

AES.WebApplication/Views/Position/Edit.cshtml
@model AES.Entities.Shared.Net45.Models.Position

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Position</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PositionId)

        <div class="form-group">
            @Html.LabelFor(model => model.PositionName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PositionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PositionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PositionDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PositionDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PositionDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StoreId, "StoreId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StoreId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StoreId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestId, "TestId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TestId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TestId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AES.WebApplication/Views/Position/Index.cshtml
@model IEnumerable<AES.Entities.Shared.Net45.Models.Position>

@{
    ViewBag.Title = "Index";
}

<h3>Available Positions</h3>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<hr />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Store.StoreLocation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Test.TestName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PositionName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PositionDesc)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Store.StoreLocation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Test.TestName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PositionName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PositionDesc)
        </td>
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.PositionId }) |*@
            @Html.ActionLink("Details", "Details", new { id=item.PositionId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PositionId })
        </td>
    </tr>
}

</table>