AES.WebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AES.WebApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "AES - commited to you";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact AES Grocers";

            return View();
        }

        public ActionResult DemoIndex()
        {
            return View();
        }
    }
}

AES.WebApplication/Controllers/PositionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using AES.Entities.Shared.Net45.Models;
using AES.WebApplication.Client;

namespace AES.WebApplication.Controllers
{
    public class PositionController : Controller
    {
        private readonly PositionSvcClient _client = new PositionSvcClient();

        public PositionController()
        {
            _client = new PositionSvcClient();
        }

        // GET: Position
        public async Task<ActionResult> Index()
        {
            IEnumerable<Position> positions = await _client.GetPositions();
            return View(positions);
        }

        // GET: Position/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Position position = await _client.GetPositionById(id);

            if (position == null)
            {
                return HttpNotFound();
            }

            return View(position);
        }

        // GET: Position/Create
        public async Task<ActionResult> Create()
        {
            IEnumerable<Store> stores = null;
            using (var client = new StoreSvcClient())
            {
                stores = await client.GetStores();
            }

            var storeTitleList = new List<string>();
            var storeTitlesQuery = from s in stores select s.StoreName;

            storeTitleList.AddRange(storeTitlesQuery);
            var storeSelectList = new SelectList(storeTitleList);

            ViewBag.StoreTitles = storeSelectList;
            ViewBag.Stores = stores;

            IEnumerable<Test> tests = null;
            using (var client = new TestSvcClient())
            {
                tests = await client.GetTests();
            }

            var testQuestionList = new List<string>();
            var testTitlesQuery = from t in tests select t.TestName;

            testQuestionList.AddRange(testTitlesQuery);
            var testSelectList = new SelectList(testQuestionList);

            ViewBag.TestQuestionList = testSelectList;
            ViewBag.Tests = tests;

            return View();
        }

        // POST: Position/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [System.Web.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "PositionId,PositionName,PositionDesc,StoreId,TestId")] Position position)
        {
            if (!ModelState.IsValid) return View(position);

            await _client.CreatePosition(position);

            return RedirectToAction("Index");
        }

        // GET: Position/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Position position = await _client.GetPositionById(id);

            IEnumerable<Store> stores = null;
            using (var client = new StoreSvcClient())
            {
                stores = await client.GetStores();
            }

            var storeTitleList = new List<string>();
            var storeTitlesQuery = from s in stores select s.StoreName;

            storeTitleList.AddRange(storeTitlesQuery);
            var storeSelectList = new SelectList(storeTitleList);

            ViewBag.StoreTitles = storeSelectList;
            ViewBag.Stores = stores;

            IEnumerable<Test> tests = null;
            using (var client = new TestSvcClient())
            {
                tests = await client.GetTests();
            }

            var testQuestionList = new List<string>();
            var testTitlesQuery = from t in tests select t.TestName;

            testQuestionList.AddRange(testTitlesQuery);
            var testSelectList = new SelectList(testQuestionList);

            ViewBag.TestQuestionList = testSelectList;
            ViewBag.Tests = tests;

            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // POST: Position/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [System.Web.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PositionId,PositionName,PositionDesc,StoreId,TestId")] Position position)
        {
            if (!ModelState.IsValid) return View(position);
            await _client.EditPosition(position);

            return RedirectToAction("Index");
        }

        // GET: Position/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Position position = await _client.GetPositionById(id);

            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // POST: Position/Delete/5
        [System.Web.Mvc.HttpPost, System.Web.Mvc.ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Position position = await _client.GetPositionById(id);
            await _client.DeletePosition(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _client.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AES.WebApplication/Views/Home/About.cshtml
@{
    ViewBag.Title = "About AES";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<p>While our stores change with the times, one thing stays the same - our commitment to Customers. By following Mr. Owner's idea for serving Customers, hundreds of associates have helped build a business that continues to thrive in the pacific northwest. With your help, we'll continue our growth, continue serving our community, and continue serving Customers for a long time to come.</p>
<p>Thank you for helping make AES what it is</p>

AES.WebApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    1303 AES Drive<br />
    Portland, OR 97202<br />
    <abbr title="Phone">P:</abbr>
    555.555.5555
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@AESGrocers.com">Support@@AESGrocers.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@AESGrocers.com">Marketing@AESGrocers.com</a>
</address>

AES.WebApplication/Views/Home/DemoIndex.cshtml
@{
    ViewBag.Title = "AES HOME";
}

<div class="jumbotron">
    <h1>AES Application Kiosk</h1>
    <!--<p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>-->
</div>

<div class="row">
    <div class="col-md-4">
        <div>
            <h2>Position</h2>
            <p>
                Allows the staffing specialist to prepare a job description linked to a questionnaire which is used to accurately filter future applicants for this job listing.
            </p>
            <p>
                <a title="This links to the Position Demo" class="btn btn-default" href="http://localhost:59701/Position">Position Demo &raquo;</a>
            </p>
        </div>
        <div>
            <h2>Questionnaire</h2>
            <p>This is a list of questions used to filter applicants. The creator may choose passing score.</p>
            <p>
                <a class="btn btn-default" href="http://localhost:59701/Test">Questionnaire Demo &raquo;</a>
            </p>
        </div>
        <div>
            <h2>Store</h2>
            <p>Stores are created to associate positions with a specific location.</p>
            <p>
                <a class="btn btn-default" href="http://localhost:59701/Store">Store Demo &raquo;</a>
            </p>
        </div>
    </div>
    <div class="col-md-4">
        <div>
            <h2>Application</h2>
            <p>Applicants fill these out so that you know not to hire them.</p>
            <p>
                <a class="btn btn-default" href="http://localhost:59701/Application">Application Demo &raquo;</a>
            </p>
        </div>
        <div>
            <h2>Permissions</h2>
            <p>Permissions control who is allowed to use certain features.</p>
            <p>
                <a class="btn btn-default" href="http://localhost:59701/UserPermission">Permission Demo &raquo;</a>
            </p>
        </div>
        <div>
            <h2>Create Questions</h2>
            <p>Create questions for use with questionnaires.</p>
            <p>
                <a class="btn btn-default" href="http://localhost:59701/QuestionAnswer">Create Question Demo &raquo;</a>
            </p>
        </div>
        <div>
            <h2>Take Questionnaire!</h2>
            <p>As a user take a questionnaire.</p>
            <p>
                <a class="btn btn-default" href="http://localhost:59701/QuestionAnswer/GetQuestionnaire">Take Questionnaire Demo &raquo;</a>
            </p>
        </div>
    </div>
</div>

AES.WebApplication/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Splash.cshtml";
    ViewBag.Title = "AES HOME";
}

<div class="splash-container">
    <div class="logo-container">
        <a href='@Url.Action("Index", "Position")'>
            <img id="AESLogo" alt="AESLogo" src="~/aes-logo.png" />
        </a>
    </div>
</div>